apiVersion: v1
kind: Service
metadata:
  name: nsqlookupd-service
  labels:
    app: nsqlookupd
spec:
  # type: LoadBalancer # use extenal IP
  type: NodePort # use NAT inside k8s
  selector:
    app: nsqlookupd
  ports:
    - name: tcp
      protocol: TCP
      port: 4160
      targetPort: 4160
    - name: http
      protocol: TCP
      port: 4161
      targetPort: 4161
